on:
  push:
    branches:
      - master

name: JS release

jobs:
  release:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: 'Setup NodeJS 20.x'
        uses: actions/setup-node@v4
        with:
          node-version: 20.x

      - name: 'Get version from package.json'
        run: |
          VERSION=$(jq -r '.version' package.json)
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "TAG_NAME=js/$VERSION" >> $GITHUB_ENV

      - name: 'Get release notes'
        id: release_notes
        run: |
          echo ::set-output name=value::"$(awk '/## ${{ env.VERSION }}/{flag=1;next}/---/{flag=0} flag' ./js/CHANGELOG.md)"

      - name: 'Create new tag'
        run: |
          git tag ${{ env.TAG_NAME }}
          git push origin ${{ env.TAG_NAME }}

      - name: 'Create Release'
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          body: ${{ steps.release_notes.outputs.value }}
          tag_name: ${{ env.TAG_NAME }}
